title: Dwijesh Reddy
logo: /images/img/Nallapa_Reddy_Dwijesh_Reddy_MSBA__186.jpg
description: Insight-driven Analyst with expertise in leveraging Python, SQL, and data visualization tools to drive business growth, streamline operations, and deliver actionable insights that enhance decision-making.
<br><br>
<a href="https://www.linkedin.com/in/dwijesh-reddy6/">LinkedIn</a> 
  /
  #<a add resume link 
  /
  #<a add repos link
#show_downloads: true
theme: jekyll-theme-minimal
