title: Dwijesh Reddy
logo: /images/img/Nallapa_Reddy_Dwijesh_Reddy_MSBA__186.jpg
description: Insight-driven Analyst with expertise in leveraging Python, SQL, and data visualization tools to drive business growth, streamline operations, and deliver actionable insights that enhance decision-making.
#show_downloads: true
theme: jekyll-theme-minimal
